# Generated by Django 5.1.1 on 2024-10-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='H&M', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Male', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category2_name', models.CharField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='menban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menban_name', models.CharField(default='kids', max_length=50)),
                ('men_ban', models.ImageField(default='cs', upload_to='statics/image')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='products', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='bn', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='men', on_delete=django.db.models.deletion.CASCADE, related_name='brand5', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='brandbnnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleb', models.CharField(default='brands', max_length=50)),
                ('s_card', models.ImageField(default='s', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='women', on_delete=django.db.models.deletion.CASCADE, related_name='brand4', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frag_name', models.CharField(default='frag', max_length=110)),
                ('brand_name', models.ForeignKey(default='men', on_delete=django.db.models.deletion.CASCADE, related_name='brand6', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='hwomencard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcard_name', models.CharField(default='women', max_length=20)),
                ('wcard_image', models.ImageField(default='kj', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='polo', on_delete=django.db.models.deletion.CASCADE, related_name='brand2', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='hwomencard2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcard2_name', models.CharField(default='boys', max_length=20)),
                ('wcard2_image', models.ImageField(default='b', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='trend', on_delete=django.db.models.deletion.CASCADE, related_name='brand1', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_cat', models.CharField(max_length=22)),
                ('shoes_banner', models.ImageField(default='sho', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='asian', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='ab', upload_to='statics/image')),
                ('title', models.TextField()),
                ('product_title', models.CharField(default='women', max_length=103)),
                ('rating', models.CharField(max_length=31)),
                ('price', models.IntegerField(null=True)),
                ('image1', models.ImageField(upload_to='statics/image')),
                ('image2', models.ImageField(upload_to='statics/image')),
                ('image3', models.ImageField(upload_to='statics/image')),
                ('image4', models.ImageField(upload_to='statics/image')),
                ('image5', models.ImageField(upload_to='statics/image')),
                ('image6', models.ImageField(upload_to='statics/image')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='app.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriesname', to='app.category')),
                ('category2_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat2name', to='app.category2')),
                ('frag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragname', to='app.fragrance')),
                ('pro_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='app.product')),
                ('shoes_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='app.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='wbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_banner', models.ImageField(default='Ab', upload_to='statics/image')),
                ('brand_name', models.ForeignKey(default='levis', on_delete=django.db.models.deletion.CASCADE, related_name='brand3', to='app.brand')),
            ],
        ),
    ]
