# Generated by Django 5.1.1 on 2024-10-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='name',
            new_name='username',
        ),
    ]
