# Generated by Django 5.1.1 on 2024-11-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
