# Generated by Django 5.1.1 on 2024-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
