# Generated by Django 5.1.1 on 2024-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sign_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='phone',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
