# Generated by Django 5.1.1 on 2024-11-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_cartitem_image_remove_cartitem_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
