# Generated by Django 5.1.1 on 2024-11-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
