# Generated by Django 5.1.1 on 2024-11-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phoneno',
            new_name='Phoneno1',
        ),
        migrations.AddField(
            model_name='order',
            name='alterPhone',
            field=models.IntegerField(default=0),
        ),
    ]
