# Generated by Django 5.1.1 on 2024-11-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contactus_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
    ]
