# Generated by Django 5.1.1 on 2024-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_wishlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(default=1, upload_to='statics/image'),
            preserve_default=False,
        ),
    ]
