# Generated by Django 5.1.1 on 2024-11-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_wishlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product_name',
        ),
    ]
