# Generated by Django 5.1.1 on 2024-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_name_wishlist_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.CharField(choices=[('NA', 'NA'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXl', 'Double Xtra Lagre')], max_length=20),
        ),
    ]
