# Generated by Django 5.1.3 on 2024-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_card_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='shoes_size',
            field=models.CharField(choices=[('UK', '7'), ('UK', '6'), ('UK', '9'), ('UK', '8'), ('UK', '5'), ('UK', '10'), ('UK', '11')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
