# Generated by Django 5.1.3 on 2024-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_card_shoes_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='shoes_size',
        ),
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.CharField(choices=[('NA', 'NA'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXl', 'Double Xtra Lagre'), ('UK', '5'), ('UK', '6'), ('UK', '7'), ('UK', '8'), ('UK', '9'), ('UK', '10'), ('UK', '11')], max_length=20),
        ),
    ]
