# Generated by Django 5.1.1 on 2024-11-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_card_shoes_size_alter_card_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='banner_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='banner_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_n', to='app.banners'),
            preserve_default=False,
        ),
    ]
