# Generated by Django 5.1.1 on 2024-11-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_banners_banner_name_card_banner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='menban_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_bn', to='app.menban'),
            preserve_default=False,
        ),
    ]
