# Generated by Django 5.1.1 on 2024-11-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_card_menban_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='titileb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titl_b', to='app.brandbnnr'),
            preserve_default=False,
        ),
    ]
