# Generated by Django 5.1.1 on 2024-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_card_titileb'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbanner',
            name='wbanner_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
