# Generated by Django 5.1.1 on 2024-11-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_wbanner_wbanner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wbanner_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wb_n', to='app.wbanner'),
            preserve_default=False,
        ),
    ]
