# Generated by Django 5.1.1 on 2024-11-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_card_wbanner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='shoes_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_cat', to='app.shoes'),
        ),
    ]
