# Generated by Django 5.1.1 on 2024-11-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_card_shoes_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wcard_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wc_nm', to='app.hwomencard'),
            preserve_default=False,
        ),
    ]
