# Generated by Django 5.1.1 on 2024-11-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_card_wcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wcard2_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wc2_n', to='app.hwomencard2'),
            preserve_default=False,
        ),
    ]
